[package]
name = "raylib"
version = "4.5.0"
authors = ["DeltaPHC <phclem@protonmail.com>", "Mia Ayeke <mia@ayeke.dev>", "Teddy Astie <tsnake@outlook.fr>"]
license = "Zlib"
readme = "../README.md"
description = "Safe Rust bindings for Raylib."
documentation = "https://docs.rs/raylib"
repository = "https://github.com/deltaphc/raylib-rs"
keywords = ["bindings", "raylib", "gamedev"]
categories = ["api-bindings", "game-engines", "graphics"]
edition = "2021"

[dependencies]
raylib-sys = { version = "= 4.5.0", path = "../raylib-sys" }
libc = "0.2.137"
lazy_static = "1.2.0"
cfg-if = "1.0.0"
serde = { version = "1.0.125", features = ["derive"], optional = true }
serde_json = { version = "1.0.64", optional = true }

[features]
nightly = []
nobuild = ["raylib-sys/nobuild"]
with_serde = ["serde", "serde_json"]
wayland = ["raylib-sys/wayland"]

[package.metadata.docs.rs]
features = ["nobuild"]
