[package]
name = "raylib-test"
version = "4.5.0"
authors = ["David Ayeke"]
edition = "2018"
license = "Zlib"
readme = "../README.md"
repository = "https://github.com/deltaphc/raylib-rs"


[dependencies]
raylib = { version = "4.6", path = "../raylib" }
lazy_static = "1.2.0"
